SELECT  [Store]
      ,[Dept]
      ,[Date_of_Sales]
      ,[Weekly_sales]
      ,[isholiday]
      ,[profit]
      ,[loss]
  FROM [vrinda].[dbo].[sales_new]
  except
  SELECT  [Store]
      ,[Dept]
      ,[Date_of_Sales]
      ,[Weekly_sales]
      ,[isholiday]
      ,[profit]
      ,[loss]
  FROM [vrinda].[dbo].[sales]